[platformio]
src_dir = firmware/src
include_dir = firmware/include
default_envs = arduino_nano_esp32

[env:arduino_nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer
    https://github.com/robopeak/rplidar_arduino.git

build_flags =
    -DCORE_DEBUG_LEVEL=1
